<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetLibVersion);$(NetStandardLibVersion)</TargetFrameworks>
    <RootNamespace>Quench</RootNamespace>
    <AssemblyName>Quench</AssemblyName>

    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>Quench</PackageId>
    <Title>Quench.NET</Title>
    <Description>Customisable exception-quenching library for .NET</Description>
    <PackageTags>dotnet;exception;quench;Synesis</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/synesissoftware/Quench.NET</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/synesissoftware/Quench.NET/blob/master/CHANGES.md</PackageReleaseNotes>

    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" PrivateAssets="All" />
  </ItemGroup>

</Project>
