<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>Quench.QuickStart</RootNamespace>
    <AssemblyName>Quench.NET.QuickStart</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Quench.NET\Quench.NET.csproj" />
  </ItemGroup>

</Project>
